name: Validate

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build:
    runs-on: python:3.9-slim
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Install deps'
        run: |
          pip install \
          pelican==4.7.2 \
          pelican-gist==0.3.4 \
          pelican-simple-footnotes==1.0.2 \
          Pygments==2.12.0

      - name: 'Validate Pelican build'
        run: |
          pelican content --fatal errors

      - name: Get changed files
        if: steps.changed-files.outputs.only_changed == 'true' && github.event_name == 'pull_request'
        id: changed-files
        uses: tj-actions/changed-files@v24.1
        with:
          files: *.md

      - name: 'Install Vale'
        if: steps.changed-files.outputs.only_changed == 'true' && github.event_name == 'pull_request'
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.20.1/vale_2.20.1_Linux_64-bit.tar.gz -O - |tar -xz

      - name: 'Validate with Vale'
        if: steps.changed-files.outputs.only_changed == 'true' && github.event_name == 'pull_request'
        run: |
          ./vale ${{steps.changed-files.outputs.all_changed_files}}

      - name: Deploy to smetj.net
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.SSH_KEY }} > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          rsync --rsh='ssh -i /tmp/id_rsa -p 33221' -r output/* publish@smetj.net:~/smetj.net
