name: Validate

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Install deps'
        run: |
          pip install \
          pelican==4.9.1 \
          pelican-gist==0.3.4 \
          pelican-simple-footnotes==1.0.2 \
          Pygments==2.16.1

      - name: 'Generate site'
        run: |
          pelican

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
